@startuml

class 入力デバイス {

}

class 出力デバイス {

}

class 商品選択ボタン {

}

class 商品ボタンのライト {

}

class 入金額表示のモニタ {

}

class お金管理部 {

}

class コイン投入口 {

}

class お釣り出口 {

}

class コイン保管庫 {

}

class 商品管理 {

}

class 商品保管庫 {

}

class 商品出口 {

}

class 商品入り口 {

}

class 商品ディスプレイ {

}



class 入金部 {
    - 入金額
    + 入金処理を行う()
}

class 表示部 {
    - 選択されている商品
    - 表示する数字
    + ボタンで商品の選択を受け付ける()
    + ディスプレイに表示する()
    + ランプを点灯する()
    + ランプを消灯する()
}

class レジスタ {
    - 選択された商品の価格
    - 各飲料の売上データ
    + 入金金額と商品価格を照らし合わせる()
    + お釣りを割り出す()
}

class おつり出口 {
    - お釣り:
    + 返却する()
}

class 商品管理部 {
    - 温度
    + 商品を冷やす()
    + 商品を温める()
}

class 商品保持部 {
    - 商品の価格
    - 商品の適正な温度
    - 在庫数
}

class 商品口 {
    + 商品排出をする()
} 

レジスタ -- 商品保持部
商品口 -- 商品保持部
おつり出口 -- レジスタ
入金部 -- レジスタ
レジスタ -- 商品管理部
表示部 -- レジスタ
@enduml

