@startuml


class 入金部 {
    - 入金を受け付ける
    + 入金処理を行う()
}

class レジスタ {
    - 入金残高を表示する
    - 各飲料の売上データを持つ
    + 入金金額を取得する()
    + 出金金額を取得する()
}

class おつり出口 {
    + 返却する()
}

class 商品管理部 {
    - 温度を持つ
    + 商品を冷やす()
    + 商品を温める()
}

class 商品保持部 {
    - 商品の価格を持つ
    - 商品の適正な温度を持つ
    - 在庫数えお持つ
    - ランプ状態を持つ
    + ランプ点灯する()
    + ランプ消灯する()
    + ボタン入力する()
}

class 商品口 {
    + 商品排出をする()
} 

商品管理部 -- 商品保持部
商品口 -- 商品保持部
おつり出口 -- レジスタ
入金部 -- レジスタ
レジスタ -- 商品管理部

@enduml

