@startuml

class 入金部 {
    - 入金総額
    + 入金処理()
    + 購入完了
}

class レジスタ {
    - 保持金額
    - 各飲料の売上データ
    + 入金金額()
    + 出勤金額()
}

class おつり出口 {
    + 返却())
}

class 商品管理部 {
    - 温度
    + 商品を冷やす()
    + 商品を温める()
}

class 商品保持部 {
    - 商品の価格
    - 商品の適正な温度
    - 在庫数
    - ランプ状態
    + ランプ点灯()
    + ランプ消灯()
    + ボタン入力()
}

class 商品口 {
    + 商品排出()
} 



@enduml

