@startuml Q01.png
title <size:18>Q01:maxmellon</size>
actor User           as user
actor AdminUser      as admin
actor VendingMachine as vending
user <|-up- admin

left to right direction

package "VendingMachineSystem" {
  usecase (buy products)    as buyCase
  usecase (charge products) as chargeCase
  usecase (Manage products) as manageCase
  usecase (heat products)   as heat
  usecase (cold products)   as cold

  user    -ri- buyCase
  admin   -ri- chargeCase
  vending -le- manageCase

  manageCase <.le. heat : <<include>>
  manageCase <.le. cold : <<include>>
}
@enduml
