@startuml Q02.png
title <size:18>Q02:maxmellon</size>
actor 顧客 as user
actor 管理者 as admin
actor 自販機 as vending

actor 販売失敗 as missSale

user <|-up- admin

left to right direction

skinparam usecase {
  BackgroundColor<<MissUseCase>> DarkSeaGreen
  BackgroundColor<<NegativeActor>> DarkSeaGreen
  BackgroundColor<<Mitigate>> YellowGreen
}

actor 釣銭切 as lostedChange <<NegativeActor>>
actor 売切   as soledOut     <<NegativeActor>>

package "自動販売機システム" {

  usecase (商品を購入する)   as buyCase
  usecase (商品を補充する)   as chargeCase
  usecase (商品を管理する)   as manageCase
  usecase (商品を温める)     as heat
  usecase (商品を冷やす)     as cold

  usecase (釣銭が切れる)     as lostChange  <<MissUseCase>>
  usecase (商品が切れる)     as lostProduct <<MissUseCase>>

  usecase (管理者に連絡する) as connectAdmin <<Mitigate>>

  user    -- buyCase
  admin   -- chargeCase

  buyCase -- lostChange  : <<threaten>>
  buyCase -- lostProduct : <<threaten>>

  buyCase .. connectAdmin : <<include>>

  lostChange  -up- missSale
  lostProduct -up- missSale

  lostChange  -down- lostedChange
  lostProduct -down- soledOut

  lostChange  -- connectAdmin <<mitigate>>
  lostProduct -- connectAdmin <<mitigate>>

  heat .. manageCase : <<include>>
  cold .. manageCase : <<include>>

  vending -right- manageCase
}
@enduml
